/*
 * Inital work to make a fully configured database from which the DB setup is deducted.
 */

-- Import data from CSV files to create the basic database structure
CREATE TABLE BEV.ADRESSE AS SELECT * FROM CSVREAD('ADRESSE.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.ADRESSE_GST AS SELECT * FROM CSVREAD('ADRESSE_GST.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.GEBAEUDE_FUNKTION AS SELECT * FROM CSVREAD('GEBAEUDE_FUNKTION.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.GEBAEUDE AS SELECT * FROM CSVREAD('GEBAEUDE.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.GEMEINDE AS SELECT * FROM CSVREAD('GEMEINDE.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.ORTSCHAFT AS SELECT * FROM CSVREAD('ORTSCHAFT.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.STRASSE AS SELECT * FROM CSVREAD('STRASSE.csv', null, 'charset=UTF-8 fieldSeparator=;');
CREATE TABLE BEV.ZAEHLSPRENGEL AS SELECT * FROM CSVREAD('ZAEHLSPRENGEL.csv', null, 'charset=UTF-8 fieldSeparator=;');

-- Remove all data
TRUNCATE TABLE BEV.ADRESSE;
TRUNCATE TABLE BEV.ADRESSE_GST;
TRUNCATE TABLE BEV.GEBAEUDE_FUNKTION;
TRUNCATE TABLE BEV.GEBAEUDE;
TRUNCATE TABLE BEV.GEMEINDE;
TRUNCATE TABLE BEV.ORTSCHAFT;
TRUNCATE TABLE BEV.STRASSE;
TRUNCATE TABLE BEV.ZAEHLSPRENGEL;
COMMIT;

-- Create primary keys where it makes sense (according to data definition of BEV)
ALTER TABLE BEV.ADRESSE ALTER COLUMN ADRCD SET NOT NULL;
CREATE PRIMARY KEY ON BEV.ADRESSE (ADRCD);

ALTER TABLE BEV.GEBAEUDE ALTER COLUMN ADRCD SET NOT NULL;
ALTER TABLE BEV.GEBAEUDE ALTER COLUMN SUBCD SET NOT NULL;
CREATE PRIMARY KEY ON BEV.GEBAEUDE (ADRCD, SUBCD);

ALTER TABLE BEV.GEMEINDE ALTER COLUMN GKZ SET NOT NULL;
CREATE PRIMARY KEY ON BEV.GEMEINDE (GKZ);

ALTER TABLE BEV.ORTSCHAFT ALTER COLUMN OKZ SET NOT NULL;
CREATE PRIMARY KEY ON BEV.ORTSCHAFT (OKZ);

ALTER TABLE BEV.STRASSE ALTER COLUMN SKZ SET NOT NULL;
CREATE PRIMARY KEY ON BEV.STRASSE (SKZ);

ALTER TABLE BEV.ZAEHLSPRENGEL ALTER COLUMN GKZ SET NOT NULL;
ALTER TABLE BEV.ZAEHLSPRENGEL ALTER COLUMN ZAEHLSPRENGEL SET NOT NULL;
CREATE PRIMARY KEY ON BEV.ZAEHLSPRENGEL (GKZ, ZAEHLSPRENGEL);

-- Create index on foreign key columns
CREATE INDEX ON BEV.ADRESSE (GKZ);
CREATE INDEX ON BEV.ADRESSE (OKZ);
CREATE INDEX ON BEV.ADRESSE (PLZ);
CREATE INDEX ON BEV.ADRESSE (SKZ);
CREATE INDEX ON BEV.ADRESSE (ZAEHLSPRENGEL);

CREATE INDEX ON BEV.ORTSCHAFT (GKZ);
CREATE INDEX ON BEV.ORTSCHAFT (OKZ);

CREATE INDEX ON BEV.STRASSE (GKZ);

CREATE INDEX ON BEV.ZAEHLSPRENGEL (GKZ);
CREATE INDEX ON BEV.ZAEHLSPRENGEL (ZAEHLSPRENGEL);

CREATE INDEX ON BEV.ADRESSE_GST (ADRCD);

CREATE INDEX ON BEV.GEBAEUDE (ADRCD);
CREATE INDEX ON BEV.GEBAEUDE (SUBCD);

CREATE INDEX ON BEV.GEBAEUDE_FUNKTION (ADRCD);
CREATE INDEX ON BEV.GEBAEUDE_FUNKTION (SUBCD);

-- Don't create foreign key contraints because data is only allowed to change during mass imports from CSV filed from BEV