/*
 * Import data from the CSV files of BEV. All existing data will be deleted in advance.
 *
 * The data files can be obtained at 
 * http://www.bev.gv.at/portal/page?_pageid=713,2601271&_dad=portal&_schema=PORTAL
 * 
 * The structure, syntax and semantics must be the same as in the version from 2015-10-08.
 */

-- ensure that not every operation is commited automatically
SET AUTOCOMMIT FALSE;

-- don't write any recovery logs
SET LOG 0;
SET UNDO_LOG 0;

-- The path to the CSV files with a trailing slash
SET @PATH=:path;

DROP VIEW IF EXISTS BEV.V_ADRESSE_DENORMALIZED;

DROP INDEX IF EXISTS BEV.INDEX_E;
DROP INDEX IF EXISTS BEV.INDEX_E7;
DROP INDEX IF EXISTS BEV.INDEX_E72;
DROP INDEX IF EXISTS BEV.INDEX_E722;
DROP INDEX IF EXISTS BEV.INDEX_E722B;
 
DROP INDEX IF EXISTS BEV.INDEX_7;
DROP INDEX IF EXISTS BEV.INDEX_71;
 
DROP INDEX IF EXISTS BEV.INDEX_8;
DROP INDEX IF EXISTS BEV.INDEX_85;
 
DROP INDEX IF EXISTS BEV.INDEX_F;
DROP INDEX IF EXISTS BEV.INDEX_F4;

DROP INDEX IF EXISTS BEV.INDEX_B;
 
DROP INDEX IF EXISTS BEV.INDEX_6;
DROP INDEX IF EXISTS BEV.INDEX_6E;
 

TRUNCATE TABLE BEV.ADRESSE;
TRUNCATE TABLE BEV.ADRESSE_GST;
TRUNCATE TABLE BEV.GEBAEUDE_FUNKTION;
TRUNCATE TABLE BEV.GEBAEUDE;
TRUNCATE TABLE BEV.GEMEINDE;
TRUNCATE TABLE BEV.ORTSCHAFT;
TRUNCATE TABLE BEV.STRASSE;
TRUNCATE TABLE BEV.ZAEHLSPRENGEL;

INSERT INTO BEV.ADRESSE SELECT * FROM CSVREAD(@PATH || 'ADRESSE.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.ADRESSE_GST SELECT * FROM CSVREAD(@PATH || 'ADRESSE_GST.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.GEBAEUDE_FUNKTION SELECT * FROM CSVREAD(@PATH || 'GEBAEUDE_FUNKTION.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.GEBAEUDE SELECT * FROM CSVREAD(@PATH || 'GEBAEUDE.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.GEMEINDE SELECT * FROM CSVREAD(@PATH || 'GEMEINDE.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.ORTSCHAFT SELECT * FROM CSVREAD(@PATH || 'ORTSCHAFT.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.STRASSE SELECT * FROM CSVREAD(@PATH || 'STRASSE.csv', null, 'charset=UTF-8 fieldSeparator=;');
INSERT INTO BEV.ZAEHLSPRENGEL SELECT * FROM CSVREAD(@PATH || 'ZAEHLSPRENGEL.csv', null, 'charset=UTF-8 fieldSeparator=;');

CREATE INDEX BEV.INDEX_E ON BEV.ADRESSE(GKZ);
CREATE INDEX BEV.INDEX_E7 ON BEV.ADRESSE(OKZ);
CREATE INDEX BEV.INDEX_E72 ON BEV.ADRESSE(PLZ);
CREATE INDEX BEV.INDEX_E722 ON BEV.ADRESSE(SKZ);
CREATE INDEX BEV.INDEX_E722B ON BEV.ADRESSE(ZAEHLSPRENGEL);
 
CREATE INDEX BEV.INDEX_7 ON BEV.GEBAEUDE_FUNKTION(ADRCD);
CREATE INDEX BEV.INDEX_71 ON BEV.GEBAEUDE_FUNKTION(SUBCD);
 
CREATE INDEX BEV.INDEX_8 ON BEV.GEBAEUDE(ADRCD);
CREATE INDEX BEV.INDEX_85 ON BEV.GEBAEUDE(SUBCD);
 
CREATE INDEX BEV.INDEX_F ON BEV.ORTSCHAFT(GKZ);
CREATE INDEX BEV.INDEX_F4 ON BEV.ORTSCHAFT(OKZ);

CREATE INDEX BEV.INDEX_B ON BEV.STRASSE(GKZ);
 
CREATE INDEX BEV.INDEX_6 ON BEV.ZAEHLSPRENGEL(GKZ);
CREATE INDEX BEV.INDEX_6E ON BEV.ZAEHLSPRENGEL(ZAEHLSPRENGEL);
 
COMMIT;

CREATE OR REPLACE VIEW BEV.V_ADRESSE_DENORMALIZED AS
SELECT nvl2(a.ADRCD, a.ADRCD, '') || '-' || nvl2(b.SUBCD, b.SUBCD, '') id, a.*, o.ORTSNAME, s.STRASSENNAME, s.STRASSENNAMENZUSATZ, s.SZUSADRBEST, g.GEMEINDENAME, b.SUBCD, b.OBJEKTNUMMER, b.HAUPTADRESSE, b.HAUSNRVERBINDUNG2, b.HAUSNRZAHL3, b.HAUSNRBUCHSTABE3, b.HAUSNRVERBINDUNG3, b.HAUSNRZAHL4, b.HAUSNRBUCHSTABE4, b.HAUSNRGEBAEUDEBEZ, b.RW RW_GEBAEUDE, b.HW HW_GEBAEUDE, b.EPSG EPSG_GEBAEUDE, b.EIGENSCHAFT, b.QUELLADRESSE QUELLADRESSE_GEBAEUDE, b.BESTIMMUNGSART BESTIMMUNGSART_GEBAEUDE
FROM 
	BEV.ADRESSE a
	JOIN BEV.STRASSE s ON a.skz = s.skz
	JOIN BEV.ORTSCHAFT o ON a.okz = o.okz
	JOIN BEV.GEMEINDE g ON a.gkz = g.gkz
	LEFT JOIN BEV.GEBAEUDE b ON a.adrcd = b.adrcd
;

COMMIT;

-- write recovery logs again
SET LOG 2;
SET UNDO_LOG 1; 

