/*
 * De-normalize the address data into the table BEV.ADRESSE_DENORMALIZED for indexing
 */

-- ensure that not every operation is commited automatically
SET AUTOCOMMIT FALSE;

-- don't write any recovery logs
SET LOG 0;
SET UNDO_LOG 0;

CREATE OR REPLACE VIEW BEV.V_ADRESSE_DENORMALIZED AS
SELECT nvl2(a.ADRCD, a.ADRCD, '') || '-' || nvl2(b.SUBCD, b.SUBCD, '') id, a.*, o.ORTSNAME, s.STRASSENNAME, s.STRASSENNAMENZUSATZ, s.SZUSADRBEST, g.GEMEINDENAME, b.SUBCD, b.OBJEKTNUMMER, b.HAUPTADRESSE, b.HAUSNRVERBINDUNG2, b.HAUSNRZAHL3, b.HAUSNRBUCHSTABE3, b.HAUSNRVERBINDUNG3, b.HAUSNRZAHL4, b.HAUSNRBUCHSTABE4, b.HAUSNRGEBAEUDEBEZ, b.RW RW_GEBAEUDE, b.HW HW_GEBAEUDE, b.EPSG EPSG_GEBAEUDE, b.EIGENSCHAFT, b.QUELLADRESSE QUELLADRESSE_GEBAEUDE, b.BESTIMMUNGSART BESTIMMUNGSART_GEBAEUDE
FROM 
	BEV.ADRESSE a
	JOIN BEV.STRASSE s ON a.skz = s.skz
	JOIN BEV.ORTSCHAFT o ON a.okz = o.okz
	JOIN BEV.GEMEINDE g ON a.gkz = g.gkz
	LEFT JOIN BEV.GEBAEUDE b ON a.adrcd = b.adrcd
;

ALTER TABLE BEV.ADRESSE_DENORMALIZED DROP PRIMARY KEY;
DROP INDEX IF EXISTS BEV.INDEX_CCA;
DROP INDEX IF EXISTS BEV.INDEX_CCA1;
DROP INDEX IF EXISTS BEV.INDEX_C;
DROP INDEX IF EXISTS BEV.INDEX_CCA15;
DROP INDEX IF EXISTS BEV.INDEX_CC;

COMMIT;

TRUNCATE TABLE BEV.ADRESSE_DENORMALIZED;
INSERT INTO BEV.ADRESSE_DENORMALIZED SELECT * FROM BEV.V_ADRESSE_DENORMALIZED;

CREATE PRIMARY KEY BEV.INDEX_BEV_AD_PK ON BEV.ADRESSE_DENORMALIZED (ID);
CREATE INDEX BEV.INDEX_CCA ON BEV.ADRESSE_DENORMALIZED (GKZ ASC);
CREATE INDEX BEV.INDEX_CCA1 ON BEV.ADRESSE_DENORMALIZED (SKZ ASC);
CREATE INDEX BEV.INDEX_C ON BEV.ADRESSE_DENORMALIZED (ADRCD ASC);
CREATE INDEX BEV.INDEX_CCA15 ON BEV.ADRESSE_DENORMALIZED (PLZ ASC);
CREATE INDEX BEV.INDEX_CC ON BEV.ADRESSE_DENORMALIZED (OKZ ASC);

COMMIT;

-- write recovery logs again
SET LOG 2;
SET UNDO_LOG 1; 

